

[settings]

#history_file = "history.txt"
#history_file = ".bash_history"
history_file = "bash_history"

# Sort history lines: true or false; must be lowercase;
sort_lines = true



[filter_rules]

# Exact match
exact_include = [

]

exact_exclude = [
  "",
  "!",
  ".",
  "cp",
  "c",
  "clear"
]


# substring match; this matches anywhere;
containing_include = [
  #"###",
]
containing_exclude = [

]


# Regex expression; regex characters should be double escaped, \\, if want to use as literal
regex_include = [
  ".*###$"  # specifically target ending with ###
]

regex_exclude = [
  "^df ",
  "^ffmpeg ",
  "^npm ",
  "^git",
  "^duplicity",
  "^yt-dlp",
  "^g ",
  # "^find ",
  "^sudo apt search",
  "^sudo apt info",
  "^sudo apt update",
  "^z ",
  "^.{1}$",    # Any single character
  "^\\.",
  "^#",
  "^!",
  "^man ",
  "^cd ",
  "^c ",
  "^hs ",
  "^~",
  "^vi ",
  "^vim ",
  "^$",
  "^,",
  "^vidir ",
  "^tree ",
  "^rm ",
  "^l ",
  "^ll ",
  "^yt-dlp",
  "^target ",
  "^source ",
  "^./",
  "^\\?",
  "^:",
  # "^[ \\t\\r\\n]*$",   # regex way to remove blank
]
